# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-23 10:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0014_auto_20150427_2315'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomeContent',
        ),
    ]
